environment:
  global:
    CONDA_INSTALL_LOCN: C:\\Miniconda36-x64

platform:
  - x64

install:
  # Add path, activate `conda` and update conda.
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda
  # Add our channels.
  - cmd: conda config --add channels defaults
  - cmd: conda config --add channels conda-forge
  - cmd: conda install --yes --quiet flang clangdev openmp cmake
  - cmd: set "PATH=%CONDA_INSTALL_LOCN%\Scripts;%CONDA_INSTALL_LOCN%;%PATH%"

build_script:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cmd: set "LIB=%CONDA_INSTALL_LOCN%\Library\lib;%LIB%"
  - cmd: set "CPATH=%CONDA_INSTALL_LOCN%\Library\include;%CPATH%"
  - cmd: cmake -DCMAKE_Fortran_COMPILER=flang -G"NMake Makefiles" .
  - cmd: nmake
  - cmd: flang.exe hello_world.f90 -o hello_world.exe
  - cmd: conda remove --yes --quiet flang openmp clangdev cmake
  - cmd: conda install --yes --quiet libflang
  - cmd: hello_world.exe
